repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/aws-samples/automated-security-helper
    rev: '1.0.9-e-16May2023' # update with the latest tagged version in the repository
    hooks:
      - id: ash
        stages: [ manual ]
        # uncomment the line below if using "finch" on MacOS
        # args: [ "-f" ]

  - repo: https://github.com/sbrunner/pre-commit-copyright
    rev: 0.7.0
    hooks:
      - id: copyright
        name: update copyright
        exclude: |
          (?x)^(
            ^\..+|
            .+\.md|
            electron/.*|
            src/data/.*|
            src/vite-env.d.ts|
            index.html|
            LICENSE|
            package.json|
            package-lock.json
            tsconfig.json|
            tsconfig.node.json|
            vite.config.ts
          )$
      - id: copyright-required
        name: require copyright
        exclude: |
          (?x)^(
            ^\..+|
            .+\.md|
            electron/.*|
            src/data/.*|
            src/vite-env.d.ts|
            index.html|
            LICENSE|
            package.json|
            package-lock.json|
            tsconfig.json|
            tsconfig.node.json|
            vite.config.ts
          )$
