name: OSML Cesium Globe Release Workflow

on:
  release:
    types: [published]

jobs:
  Build_NPM:
    uses: ./.github/workflows/npm-build.yml
    secrets: inherit
  Notify_Guidance_Repo:
    needs: [Build_NPM]
    uses: ./.github/workflows/notify-guidance-repo.yml
    secrets: inherit
